class Strings {
  static const String APP_NAME = "Burc Rehperi";

  static const List<String> BURC_ADLARI = [
    "Koch",
    "Boga",
    "Ikizler",
    "Yengec",
    "Aslan",
    "Basak",
    "Terazi",
    "Akrep",
    "Yay",
    "Oglak",
    "Kova",
    "Balik"
  ];
  static const List<String> BURC_TARIHLERI = [
    "21 Mart - 20 Nisan",
    "21 Nisan - 21Mayis",
    "22 Mayis - 22 Haziran",
    "22 Haziran - 22 Temmuz",
    "23 Temmuz - 22 Agustos",
    "23 Augustos - 22 Eylul",
    "23 Eylul - 22 Ekim",
    "23 Ekim - 21 Kasim",
    "22 Kasim - 21 Aralik",
    "22 Aralik - 21 Ocak",
    "22 Ocak - 19 Subat",
    "20 Subat - 20 Mart"
  ];
  static const List<String> BURC_GENEL_OZELLIKLERI = [
    "\t Genel ozellikleri\n\n",
    "\tSembolü: Koç \n\n",
    "\tElementi: Ateş \n\n",
    "\tNiteliği: Kardinal \n\n",
    "\tYönetici gezegeni: Mars (savaş ve enerji gezegeni) \n\n",
    "\tRenk: Kırmızı \n\n",
    "\tGün: Salı \n\n",
    "\tUğurlu sayılar: 1,9 \n\n",
    "\tUğurlu taşları: Opal, Turmalin, Yakut, Jasper, Akik \n\n",
    "\tVücutta tekabül ettiği yer: Baş ve yüz \n\n",
    "\tOlumlu özellikleri: Enerjik, cesaret verici, durdurulamaz, cesur, adanmış, kahraman, şefkatli\n\n",
    "\tOlumsuz özellikleri: Kibirli, benmerkezci, itkisel, buyurgan, inatçı, umursamaz, kıskanç\n\n",
    "\tEn sevdiği şeyler: Rekabetçi oyunlar, rahat giysiler, yolculuk, tartışmak, kendini şaşırtıcı\n\n",
    "\tNefret ettiği şeyler: Görmezden gelinmek, dar alanlar, kaybetmek, “hayır” kelimesi, hareketsizlik, gecikmeler \n\n",
    "\tGizli tutkuları: Bir numara olmak \n\n",
    "\t Genel ozellikleri\n\n",
    "\tSembolü: Boğa \n\n",
    "\tElementi: Toprak \n\n",
    "\tNiteliği: Sabit \n\n",
    "\tYönetici gezegeni: Venüs (güzelliğin ve aşkın gezegeni) \n\n",
    "\tRenk: Yeşil, pembe \n\n",
    "\tGün: Cuma, Pazartesi \n\n",
    "\tUğurlu sayılar: 6, 4 \n\n",
    "\tUğurlu taşları: Turkuaz taşı, Topaz taşı, Pembe Kuvars, Safir, Yeşim\n\n",
    "\tVücutta tekabül ettiği yer: Boyun, boğaz, çene \n\n",
    "\tOlumlu özellikleri: Sabırlı, düzenli, yardımcı, romantik, özenli, adanmış\n\n",
    "\tOlumsuz özellikleri: Fazla hoşgörülü, inatçı, tembel, fazla ihtiyatlı\n\n",
    "\tEn sevdiği şeyler: Fotoğraf, dağlar, güzel müzik, gurme yemek, yemek pişirmek, bahçecilik, romans, kaliteli giysiler,\n\n",
    "\tNefret ettiği şeyler: Acele ettirilmek, parayı israf etmek, kirli şeyler, oteller, ani değişiklikler, engeller, güvensizlik\n\n",
    "\tGizli tutkuları: Her şeyin en iyisine sahip olmak\n\n",
    "\tGenel ozellikleri \n\n",
    "\tSembolü: İkizler \n\n",
    "\tElementi: Hava \n\n",
    "\tNiteliği: Değişken \n\n",
    "\tYönetici gezegeni: Merkür (iletişim ve haberleşmenin gezegeni)\n\n",
    "\tRenk: Açık yeşil, sarı \n\n",
    "\tGün: Çarşamba\n\n",
    "\tUğurlu sayılar: 5, 7 \n\n",
    "\tUğurlu taşları: Akuamarin, Akik, Topaz, Sitrin, Turmalin \n\n",
    "\tVücutta tekabül ettiği yer: Omuzlar, eller ve kollar\n\n",
    "\tOlumlu özellikleri: Etkileyici, özgün, iş bilen, alımlı, akıllı, maceracı\n\n",
    "\tOlumsuz özellikleri: Vesveseli, dengesiz, iki yüzlü, yargılayıcı, depresif\n\n",
    "\tEn sevdiği şeyler: Müzik, kitaplar, dergiler, sohbet etmek, kısa gezintiler\n\n",
    "\tNefret ettiği şeyler: Yalnız olmak, sınırlandırılmak, tekrar ve rutin, dar görüşlü insanlar, geleneksel moda, otorite figürleri, sessizlik\n\n",
    "\tGizli tutkuları: Tüm cevapları bulmak \n\n",
    "\tGenel ozellikleri \n\n",
    "\tSembolü: Yengeç \n\n",
    "\tElementi: Su \n\n",
    "\tNiteliği: Kardinal (öncü) \n\n",
    "\tYönetici gezegeni: Ay (duyguları ve ruhsal durumları yöneten gök cismi)\n\n",
    "\tRenk: Beyaz \n\n",
    "\tGün: Pazartesi, Perşembe \n\n",
    "\tUğurlu sayılar: 2, 3 \n\n",
    "\tUğurlu taşları: Akuamarin, Ay taşı, Kuvars kristali, Safir Taşı, Zümrüt\n\n",
    "\tVücutta tekabül ettiği yer: Göğüs, mide \n\n",
    "\tOlumlu özellikleri: Yardımsever, sabırlı, merhametli, anaç, romantik, yaratıcı\n\n",
    "\tOlumsuz özellikleri: Dedikoducu, burnu havada, ketum, aşırı duyarlı, fazla rekabetçi\n\n",
    "\tEn sevdiği şeyler: Gurme yemekler, salon sporları, ev partileri, çocuklar, müze ve sanat galeriler, evde yapılan hobiler, denize girmek, sevdiklerine yardım etmek\n\n",
    "\tNefret ettiği şeyler: Pejmürde giysiler, uluorta konuşmak, acele ettirilmek, yabancı insanlar, özel hayatını anlatmak\n\n",
    "\tGizli tutkuları: Arkadaşlarına ve ailelerine göz kulak olmak\n\n",
    "\tGenel ozellikleri \n\n",
    "\tSembolü: Aslan \n\n",
    "\tElementi: Ateş \n\n",
    "\tNiteliği: Sabit \n\n",
    "\tYönetici gezegeni: Güneş \n\n",
    "\tRenk: Altın sarısı, sarı, turuncu \n\n",
    "\tGün: Pazar \n\n",
    "\tUğurlu sayılar: 1, 3 \n\n",
    "\tUğurlu taşları: Akik, Kehribar, Oniks, Topaz taşı, Kaplangözü\n\n",
    "\tVücutta tekabül ettiği yer: Kalp, üst sırt, omurga\n\n",
    "\tOlumlu özellikleri: Cesur, kibar, cömert, sadık, koruyucu, dobra, eğlenceli\n\n",
    "\tOlumsuz özellikleri: Küstah, müsrif, özensiz, taş kalpli, kıskanç, saldırgan\n\n",
    "\tEn sevdiği şeyler: Kameralar, şarkı söylemek, yakınlık kurmak, iltifat, güzel kıyafetler, tiyatro, pahalı şeyler, tatiller\n\n",
    "\tNefret ettiği şeyler: Görmezden gelinmek, yavan yemekler, yalnız kalmak, vedalar, kral-kraliçe muamelesi görmemek\n\n",
    "\tGizli tutkuları: Dünyayı yönetmek \n\n",
    "\tGenel ozellikleri \n\n",
    "\tSembolü: Bakire kadın \n\n",
    "\tElementi: Toprak \n\n",
    "\tNiteliği: Değişken \n\n",
    "\tYönetici gezegeni: Merkür (iletişim gezegeni) \n\n",
    "\tRenk: Gri, bej, açık sarı \n\n",
    "\tGün: Çarşamba \n\n",
    "\tUğurlu sayılar: 5, 14 \n\n",
    "\tUğurlu taşları: Akik, Kehribar, Jasper, Turmalin, Yeşim \n\n",
    "\tVücutta tekabül ettiği yer: Mide, bel, sindirim sistemi\n\n",
    "\tOlumlu özellikleri: Adanmış, becerikli, yardımsever, çalışkan, hazırcevap, pratik\n\n",
    "\tOlumsuz özellikleri: Vaaz verme meraklısı, kendi kendine zarar verme, kendine acıma, şekilci, eleştirel\n\n",
    "\tEn sevdiği şeyler: Bilgisayarlar, dergiler, uzun banyolar, konserler, çocukluk arkadaşları, hayvanlar, sağlıklı yemekler, kitaplar, doğa, temizlik\n\n",
    "\tNefret ettiği şeyler: Tembel ya da kaba insanlar, evden ayrılmak, yardım istemek\n\n",
    "\tGizli tutkuları: Kahraman olmak \n\n",
    "\tGenel ozellikleri \n\n",
    "\tSembolü: Adalet terazisi \n\n",
    "\tElementi: Hava \n\n",
    "\tNiteliği: Kardinal \n\n",
    "\tYönetici gezegeni: Venüs (güzelliğin, lüksün ve aşkın gezegeni)\n\n",
    "\tRenk: Pembe, yeşil \n\n",
    "\tGün: Cuma \n\n",
    "\tUğurlu sayılar: 4, 6 \n\n",
    "\tUğurlu taşları: Yeşim, Topaz, Pembe Kuvars, Turmalin, Akuvamarin\n\n",
    "\tVücutta tekabül ettiği yer: Alt sırt, popo \n\n",
    "\tOlumlu özellikleri: Çekici, sevimli, adil, cana yakın, paylaşımcı, romantik\n\n",
    "\tOlumsuz özellikleri: Faydasız, kararsız, aşırı duygusal, manipülatif, şımarık, kuruntulu\n\n",
    "\tEn sevdiği şeyler: Büyük konserler, şiir, pahalı mücevherler, tasarım giysiler, iyi yemek, uyum, nezaket, gezmek\n\n",
    "\tNefret ettiği şeyler: Donuk ya da pratik insanlar, zorbalık, bir karar vermeye zorlanmak, “belki”ler, şiddet, adaletsizlik, gevezelik, şekilcilik\n\n",
    "\tGizli tutkuları: Sevmek ve sevilmek \n\n",
    "\tGenel ozellikleri \n\n",
    "\tSembolü: Akrep \n\n",
    "\tElementi: Su \n\n",
    "\tNiteliği: Sabit \n\n",
    "\tYönetici gezegeni: Plüton (gücün ve yenilenmenin gezegeni) \n\n",
    "\tRenk: Kırmızı, Bordo, Siyah \n\n",
    "\tGün: Salı \n\n",
    "\tUğurlu sayılar: 8, 11, 18, 22 \n\n",
    "\tUğurlu taşları: Yakut, Opal, Lal \n\n",
    "\tVücutta tekabül ettiği yer: Genital organlar \n\n",
    "\tOlumlu özellikleri: Sabırlı, derinlemesine bilgi sahibi, disiplinli, dikkatli\n\n",
    "\tOlumsuz özellikleri: Kindar, asıl niyetini gizleyen, herkese karşı güvensiz\n\n",
    "\tEn sevdiği şeyler: Gizemlilik, tehlike havası, underground müzik, tıbbi bitkiler, lateks veya deri kıyafetler\n\n",
    "\tNefret ettiği şeyler: Basit insanlar, samimiyetsizlik, özel sorular, başkasının evinde yaşamak zorunda olmak\n\n",
    "\tGizli tutkuları: Başkalarının hayatına dair her şeyi bilmek, tam bir kontrole sahip olmak.\n\n",
    "\tGenel ozellikleri \n\n",
    "\tSembolü: Okçu \n\n",
    "\tElementi: Ateş \n\n",
    "\tNiteliği: Değişken \n\n",
    "\tYönetici gezegeni: Jüpiter (şans ve ilerlemenin gezegeni) \n\n",
    "\tRenk: Mavi \n\n",
    "\tGün: Perşembe \n\n",
    "\tUğurlu sayılar: 3, 7, 9 \n\n",
    "\tUğurlu taşları: Safir, Lapis, Akik, Ametist, Lal \n\n",
    "\tVücutta tekabül ettiği yer: Kalça, iç uyluk \n\n",
    "\tOlumlu özellikleri: Dürüst, tarafsız, iyimser, coşkulu, cesaretlendirici, adanmış\n\n",
    "\tOlumsuz özellikleri: Tartışmacı, umursamaz, tuhaf, vaaz verme meraklısı, nezaketsiz, kendinden çok emin\n\n",
    "\tEn sevdiği şeyler: Meydan okumak, flört etmek, evcil hayvanlar, yolculuk, gülmek, kitaplar, ilham veren öyküler, özgürlük, dışarıda olmak\n\n",
    "\tNefret ettiği şeyler: Önyargı, rutin, kurallar, can sıkkınlığı, meseleleri çok ciddiye almak, “yapamazsın” sözü, yapışkan insanlar, sınırlandırılmak, ayrıntılar\n\n",
    "\tGizli tutkuları: Kuralları koymak \n\n",
    "\tGenel ozellikleri \n\n",
    "\tSembolü: Oğlak \n\n",
    "\tElementi: Toprak \n\n",
    "\tNiteliği: Kardinal (öncü) \n\n",
    "\tYönetici gezegeni: Satürn (disiplinin ve olgunluğun gezegeni) \n\n",
    "\tRenk: Kahverengi, siyah \n\n",
    "\tGün: Cumartesi \n\n",
    "\tUğurlu sayılar: 4, 8 \n\n",
    "\tUğurlu taşları: Turmalin, Zirkon, Yakut, Lal, Malahit \n\n",
    "\tVücutta tekabül ettiği yer: Diz, deri, kemikler ve dişler\n\n",
    "\tOlumlu özellikleri: Sadık, ailesine düşkün, çalışkan, adanmış, dürüst, korkusuz\n\n",
    "\tOlumsuz özellikleri: Kötümser, bağışlamaz, soğuk, maddiyatçı, burnu havada, umutsuz\n\n",
    "\tEn sevdiği şeyler: Kartvizitler, hedefler, iş unvanları, görev yapmak, aile, gelenek\n\n",
    "\tNefret ettiği şeyler: İstifa etmek, uluorta bağırmak, dikkatsizlik kaynaklı hatalar, kılavuz olmadan yolculuk yapmak, bir şeyi sırf yapmış olmak için yapmak\n\n",
    "\tGizli tutkuları: Her ihtiyacı karşılamak\n\n",
    "\tGenel ozellikleri \n\n",
    "\tSembolü: Kova \n\n",
    "\tElementi: Hava \n\n",
    "\tNiteliği: Sabit \n\n",
    "\tYönetici gezegeni: Uranüs (özgünlüğün gezegeni) \n\n",
    "\tRenk: Turuncu, gece mavisi, yeşil \n\n",
    "\tGün: Pazar \n\n",
    "\tUğurlu sayılar: 4, 7, 11,22, 29 \n\n",
    "\tUğurlu taşları: Yeşim, Obsidyen, Zirkon, Akuamarin, Ametist \n\n",
    "\tVücutta tekabül ettiği yer: Ayak bilekleri \n\n",
    "\tOlumlu özellikleri: Bağımsız, özgün, insani, açık fikirli, adil, mantıklı\n\n",
    "\tOlumsuz özellikleri: Tavizsiz, gösterişçi, söz tutmama \n\n",
    "\tEn sevdiği şeyler: Arkadaşlarıyla eğlenmek, yardım etmek, entelektüel ortamlar, bilim-kurgu, bağımsız filmler\n\n",
    "\tNefret ettiği şeyler: Sınırlar, kırıcı sözler, yalnızlık, sıkıcı insanlar, karşıt görüşlü insanlar, adaletsizlik, ilgi manyağı insanlar\n\n",
    "\tGizli tutkuları: Tamamen özgür olmak \n\n",
    "\tGenel ozellikleri \n\n",
    "\tSembolü: Balık \n\n",
    "\tElementi: Su \n\n",
    "\tNiteliği: Değişken \n\n",
    "\tYönetici gezegeni: Neptün (hayal gücünün gezegeni), Jüpiter (şans ve ilerlemenin gezegeni)\n\n",
    "\tRenk: Leylak, mor, eflatun, su yeşili \n\n",
    "\tGün: Perşembe \n\n",
    "\tUğurlu sayılar: 3, 9 \n\n",
    "\tUğurlu taşları: Akuamarin, Ay taşı, Ametist, Kuvars, Pembe Kuvars\n\n",
    "\tVücutta tekabül ettiği yer: Ayaklar \n\n",
    "\tOlumlu özellikleri: Romantik, yardımsever, bilge, rahatlatıcı, yaratıcı \n\n",
    "\tOlumsuz özellikleri: Saflık, kendine acıma, gerçeklikten kopukluk, kendine zarar verme, bağımlı\n\n",
    "\tEn sevdiği şeyler: Yalnız kalmak, uyumak, müzik dinlemek, şarkı söylemek, yazmak, aşık olmak, görsel medya, yüzmek, spiritüalizm, yürümek, burnunun dikine gitmek, içindeki karanlığı bastırmaya çalışmak, ağlamak. \n\n",
    "\tNefret ettiği şeyler: Gerçeklik, gün ışığı, kötü tasarım, gürültülü müzik, ukalalık, eleştirilmek, her türlü gaddarlık, geçmişe takılıp kalmak, derdini anlatamamak ve anlaşılamamak, kale alınmamak, ruhsal ve fiziksel olarak kısıtlanmak\n\n",
    "\tGizli tutkuları: Koşulsuz aşkı bulmak \n\n"
  ];
}
